### ISSUE TITLE
[CORE] Sort Based shuffle writer

### ISSUE THREAD

**Issue by dtx0624** [oap-project/gluten#1240]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps developers understand the context and *why* for this feature, in addition to  the *what*)

Spark supports both hash based and sort based shuffle writer, and currently only hash based writer implemented.
Also, sort based shuffle writer is not mentioned in [Gluten-Velox] To do list in 2023.
I am interested in how you guys think about this feature in Gluten.

**Describe the solution you'd like**
Implement a sort based shuffle writer

**Describe alternatives you've considered**

**Additional context**

**Comment by FelixYBW** [comment]
The root cause is sort operation isn't columnar friendly. serializing or materializing the columnar batch is much more expensive than row format. Row format data is one gather operation (random read, sequential write), but columnar format has one gather operations for each column.

Compared to Vanilla Spark, we still have the small file issue, currently we spill each record batch for every reducer, then we merge the spilled files into a large file. But since Gluten occupied muc less memory than Vanilla Spark, so the small files are actually cached into page cache and doesn't cause the small file issue. 
This PR is going to solve the small file issue: https://github.com/oap-project/gluten/pull/881. In the PR we are going to spill when memory is not enough, then spill all the reducer's recordbatch into the same large file order by reducer ID. Then we merge the ordered spill files into one large file when split stop. It's aligned with Vanilla Spark's behavior. But we don't sort reducer id every row, instead we split by hash then sort by reducer id. Because Gluten's more efficient memory usage, it can cache more data and spill less files than vanilla Spark. Compared to current solution, it actually move the cached data from page cache to user managed memory, and avoid the file operations.
