### ISSUE TITLE
[CH] HiveTableScanTransform cann't read child dirs files

### ISSUE THREAD

**Issue by loneylee** [oap-project/gluten#2029]
**Describe the bug**
`InMemoryFileIndex` list files not use `recursiveFileLookup` paramters.

**reproduce**
Read file path has sub dirs like 

* root path
  * child dir path
    *  fles

**Comment by zheniantoushipashi** [comment]
Because the logic implemented by the current HiveTableScanExec is different from that of Vanilla spark,

gluten HiveTableScanExec uses fileIndex to get file list
However, Vanilla spark HiveTableScanExec uses FileInputFormat in HadoopRDD to list files in the list file, which is controlled by spark.hadoop.mapreduce.input.fileinputformat.input.dir.recursive parameter

So if you want to implement similar logic, you can implement a similar logic in fileIndex, and add a switch. When it is turned on, you can traverse the directory recursively when there is or is not PartitionCol. Currently, fileIndex is used for spark sessions. recursiveFileLookup is enabled in option, if there is no PartitionCol, it will traverse recursively, if there is PartitionCol, it will throw an exception
