### ISSUE TITLE
error "Unable to locate package *thrift*" when run ./build_velox.sh

### ISSUE THREAD

**Issue by ray-andrew** [oap-project/gluten#2433]
**Describe the bug**
when I try to build velox backend, there is an error below "Unable to locate package *thrift*".
Reading state information... Done
297 packages can be upgraded. Run 'apt list --upgradable' to see them.
+ sudo apt install -y uuid-dev libuuid1 libgsasl7-dev libkrb5-dev libxml2-dev libiberty-dev '*thrift*' g++ cmake ccache ninja-build checkinstall git libssl-dev libboost-all-dev libicu-dev libdouble-conversion-dev libgoogle-glog-dev libbz2-dev libgflags-dev libevent-dev liblz4-dev libzstd-dev libsnappy-dev liblzo2-dev bison flex tzdata wget
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package *thrift*

**To Reproduce**
cd /path_to_gluten/ep/build-velox/src
# get velox and compile
./get_velox.sh   (it run successfully)
./build_velox.sh  
when run build_velox.sh will get error above

**Comment by zombie0826** [comment]
Hi，have you successfully solved the problem of./build_velox.sh? @ray-andrew

**Comment by Hattonuri** [comment]
I ran into the same problem

from this docs https://github.com/oap-project/gluten/blob/main/docs/get-started/Velox.md#build-gluten-with-velox-backend
I use sudo -E ./dev/buildbundle-veloxbe.sh (sudo because the script uses apt, -E to preserve JAVA_HOME)

and get

Building dependency tree
Reading state information... Done
213 packages can be upgraded. Run 'apt list --upgradable' to see them.
sudo --preserve-env apt install -y g++ cmake ccache uuid-dev libuuid1 libgsasl7-dev libkrb5-dev libxml2-dev libiberty-dev '*thrift*' ninja-build checkinstall libc-ares-dev libcurl4-openssl-dev libssl-dev libboost-all-dev libicu-dev libdouble-conversion-dev libfmt-dev libgoogle-glog-dev libbz2-dev libgflags-dev libevent-dev liblz4-dev libzstd-dev libsnappy-dev libsodium-dev libthrift-dev liblzo2-dev libelf-dev libdwarf-dev bison flex libfl-dev tzdata wget
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package *thrift*

this `*thrift*` is from this line
https://github.com/oap-project/gluten/blob/97bd0f61703d6f94f4eced0a277a85012e7df960/ep/build-velox/src/get_velox.sh#L88

because when I comment it the script proceeds and fails on folly compilation

`/usr/include/fmt/core.h:1393:18:   required from 'fmt::v6::format_arg_store<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<Char> >, Char>, typename std::remove_reference<Args>::type ...> fmt::v6::internal::make_args_checked(const S&, fmt::v6::remove_reference_t<Args>& ...) [with Args = {std::chrono::duration<long int, std::ratio<1, 1000> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; S = char [9]; Char = char]'
/usr/include/fmt/core.h:1478:44:   required from 'std::__cxx11::basic_string<Char> fmt::v6::format(const S&, Args&& ...) [with S = char [9]; Args = {std::chrono::duration<long int, std::ratio<1, 1000> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}; Char = char]'
/home/dstasenko/gluten/ep/build-velox/build/velox_ep/folly/folly/Singleton.cpp:457:46:   required from here
/usr/include/fmt/compile.h:524:13: error: request for member 'format' in 'cf', which is of non-class type 'const char [6]'
  524 |   return cf.format(out, args...);
      |          ~~~^~~~~~`

Which i think is another problem not related to this

I use ubuntu 20.04 for build

**Comment by Hattonuri** [comment]
@zombie0826 could you reopen this issue please?
