### ISSUE TITLE
Why use glutenAlloc only for allocateBytes and freeBytes?

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#2556]
I see here has a short comments, but it's still confused me.
https://github.com/oap-project/gluten/blob/ec0c93a907e80c664d5507ac3a4bd1276d078baf/cpp/velox/memory/VeloxMemoryPool.cc#L31-L33

Why we use glutenAlloc for these two methods?
https://github.com/oap-project/gluten/blob/ec0c93a907e80c664d5507ac3a4bd1276d078baf/cpp/velox/memory/VeloxMemoryPool.cc#L67-L75

CC @zhztheplayer

**Comment by zhztheplayer** [comment]
Thanks for opening this ticket. 

As you saw, the code is historic and it needs some improvement.

We wanted to takeover all the allocations including the large ones from Velox but since we only had limited time to do the coding, we ended up affecting only these two functions.  In future we definitely should do more than what is done here so that we can easily replace the system calls with optimized implementations.

**Comment by zhztheplayer** [comment]
> I see here has a short comments, but it's still confused me.

Please ignore the comment, it's out of date.

**Comment by Yohahaha** [comment]
Thanks for reply.

> In future we definitely should do more than what is done here so that we can easily replace the system calls with optimized implementations.

So, veloxAlloc will be replaced with glutenAlloc in the future, right?

**Comment by zhztheplayer** [comment]
> So, veloxAlloc will be replaced with glutenAlloc in the future, right?

Yes, ideally all the allocations should be routed to glutenAlloc.

**Comment by Yohahaha** [comment]
Thanks!
