### ISSUE TITLE
[VL] Make Backend be stateful to hold all native resources

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#3040]
### Why

Gluten use lots of static concurrent map to hold each kind of resources, like batch, iterator ref, etc, and share these in process wide. It's hard to limit these usage and decide the release order, and each map's entry may contains shared pointer that make resource lifecycle management more complexity.

### Proposal

Introduce TaskContext concept in native as a computation layer context, it holds all references needed by computation, such as batches, iterators. After that, java side can only see TaskContext and use it to interact with native resources, java side create TaskContext at computation fragment begin (scan, row2column, shuffle read), delete TaskContext at end (shuffle write, column2row), so all native resources could have a clearly boundary.

There are two ways to implement:
1. Remove static concurrent maps and move each kinds of instances to TaskContext, expose API such as addXXXInstance/releaseXXXInstance for use.
2. TaskContext hold MemoryManager and Backend instance, expose all needed API.

**Comment by Yohahaha** [comment]
@zhztheplayer

**Comment by Yohahaha** [comment]
I suppose the usage of TaskContext would like below, and in java side, provide createContext/tmpContext API of NativeTaskContext class.
```c++
JNIEXPORT jlong JNICALL Java_io_glutenproject_vectorized_NativeRowToColumnarJniWrapper_init( // NOLINT
    JNIEnv* env,
    jobject,
    jlong cSchema,
    jlong contextRef) {
  JNI_METHOD_START
  TaskContext* taskContext = reinterpret_cast<TaskContext*>(contextRef);
  GLUTEN_CHECK(taskContext != nullptr, "TaskContext should not be null.");
  auto backend = taskContext->getBackend();
  auto memoryManager = taskContext->getMemoryManager();
  auto converter = backend->getRowToColumnarConverter(memoryManager, reinterpret_cast<struct ArrowSchema*>(cSchema));
  return taskContext->addR2CInstance(converter);
  JNI_METHOD_END(-1)
}
```

@zhztheplayer

**Comment by zhztheplayer** [comment]
Thanks.

Overall the design looks OK, besides let's avoid passing memory manger to the factory functions.

```cpp
JNIEXPORT jlong JNICALL Java_io_glutenproject_vectorized_NativeRowToColumnarJniWrapper_init( // NOLINT
    JNIEnv* env,
    jobject,
    jlong cSchema,
    jlong contextRef) {
  JNI_METHOD_START
  TaskContext* taskContext = reinterpret_cast<TaskContext*>(contextRef);
  GLUTEN_CHECK(taskContext != nullptr, "TaskContext should not be null.");
  auto backend = taskContext->getBackend();
  auto converter = backend->getRowToColumnarConverter(reinterpret_cast<struct ArrowSchema*>(cSchema));
  return taskContext->addR2CInstance(converter);
  JNI_METHOD_END(-1)
}
```

Probably this is enough.

Furthermore, I doubt whether this new abstraction `TaskContext` is needed if we already make `Backend` instances contextual in new design. Worth trying the approach using `Backend` as the context between JNI:

```cpp
JNIEXPORT jlong JNICALL Java_io_glutenproject_vectorized_NativeRowToColumnarJniWrapper_init( // NOLINT
    JNIEnv* env,
    jobject,
    jlong cSchema,
    jlong backendRef) {
  JNI_METHOD_START
  Backend* backend = reinterpret_cast<Backend*>(backendRef);
  GLUTEN_CHECK(backend != nullptr);
  return backend->createRowToColumnarConverter(reinterpret_cast<struct ArrowSchema*>(cSchema));
  JNI_METHOD_END(-1)
}
```

**Comment by Yohahaha** [comment]
> Furthermore, I doubt whether this new abstraction TaskContext is needed if we already made Backend instances contextual in new design. Worth trying the approach using Backend directly as the context between JNI:

That's great and I have same thoughts on this, indeed `Backend` is enough, Backend concept was stateless before, we can refactor it to stateful.

**Comment by Yohahaha** [comment]
> > Furthermore, I doubt whether this new abstraction TaskContext is needed if we already made Backend instances contextual in new design. Worth trying the approach using Backend directly as the context between JNI:
> 
> That's great and I have same thoughts on this, indeed `Backend` is enough, Backend concept was stateless before, we can refactor it to stateful.

Do we agree on that? any more concern or opinions? @zhztheplayer

**Comment by zhztheplayer** [comment]
So far so good. Thanks!

**Comment by Yohahaha** [comment]
>  let's avoid passing memory manger to the factory functions.

Do you think Backend should not hold memory manager?

What I expected is Backend hold memory manager and all kinds of resources map, when invoke Backend#release in java side, it will release memory manager too, in other word, Backend control memory manager's lifecycle.

**Comment by zhztheplayer** [comment]
I'll try proposing some basic designs around the new API. This can be a individual PR and we can then use more PRs to move current components to it, for example, the native memory manager.

The proposed changes:

The 1st patch

1. In C++, rename `VeloxInitializer` to `VeloxBackend`, this could make the code align with Java side "backend" definition that indicates a global factory or global metadata storage at process wise.
2. In C++, introduce a new context API whose lifecycle aligns with Spark `TaskContext`. I would suggest using name `ExecutionContext` (and VeloxExecutionContext as derived name). `TaskContext` would also be a choice but it collides with Spark's `TaskContext` so that we may have to use `NativeTaskContext` in Java which looks a little bit tedios.
  (Besides, Velox has `ExecCtx`. We use longer name that it to distinguish with it)
3. In Java, introduce a mirrored structure `ExecutionContext` to which the C++ side `ExecutionContext` can bind. The objects should be managed by TaskResouceRegistry.
4. In C++, move the APIs in old `VeloxBackend` class to `ExecutionContext`. There were two stateful members `inputIters_` and `veloxPlan_`, we may manage to eliminate them in the new class.
5. Change C++ and Java code, to pass `ExecutionContext` through the JNI APIs that requires for it.

The 2st patch:

1. In C++, move the concurrent maps (except for memory manager), from JniWrapper to `ExecBackend`. The concurrency doesn't apply to ExecutionContext so unordered_map may be enough.

TODOs in future:

1. Develop a way to initialize `MemoryManager` in `ExecutionContext`'s initialization. Spiller part will be tricky so we put this into TODOs.

After this refactor, we expect JniWrapper would be less coupled with the actual query execution procedure. We may get some bonuses in C++ unit testing from this kind of decoupling, I am not sure, but it should be expected.

@Yohahaha

**Comment by Yohahaha** [comment]
@zhztheplayer would you post the design in a new issue? then I will close this.
