### ISSUE TITLE
[VL] Flushable distinct agg caused correctness issue

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#4421]
### Backend

VL (Velox)

### Bug description

TPC-DS q38 has distinct agg, when partial distinct is flushed, final result is incorrect.

flushed             |  unflushed
:-------------------------:|:-------------------------:
![](https://github.com/oap-project/gluten/assets/34979747/37e6ab25-7ccf-420f-b059-7d04a53de465)  |  ![](https://github.com/oap-project/gluten/assets/34979747/72afa9b8-d44b-4cb9-9daf-be07e4ce73a4)

expect: [26056]
actual: [26131]

### Spark version

None

**Comment by rui-mo** [comment]
It seems the aggregation before partial_count should not be flushable. Can we fully rely on whether the data being directly sent to exchange to decide whether flushable aggregation can be generated? cc @zhztheplayer

**Comment by zhztheplayer** [comment]
Thank you for reporting @Yohahaha . I think this is very likely similar to the possible corner case I mentioned in https://github.com/oap-project/gluten/pull/4312#discussion_r1446801548

>  if partial aggregation is already handing data that is partitioned by the ~~exchange~~ (aggregate) keys

We'd enhance FlushableAggregateRule to handle this case.

**Comment by zhztheplayer** [comment]
> When agg function is empty, we may not use flushable agg which may produce duplicate rows.

Flushing on distinct aggregation can be useful, e.g., do flush on scan-side then do final distinct on reducers. The problem here is Spark has specialized logic on count(distinct), however if we think it generally it's about the aggregate key distribution. If there is an exchange on the exit side of aggregation, and the exchange would have chance to redistribute the data populated in the same aggregate group, to different reducers, the partial aggregation can be considered safe to flush.

**Comment by zhztheplayer** [comment]
Update: The issue should impact Spark version >= 3.3
