### ISSUE TITLE
[VL] Shuffle data size change

### ISSUE THREAD

**Issue by zhli1142015** [oap-project/gluten#4576]
### Backend

VL (Velox)

### Bug description

Hello we observed shuffle data size changed lots between bits 1/15 and 1/26. We observed some regression with this change in our TPCDS query24a.
Before:
Left Shuffle:
![image](https://github.com/oap-project/gluten/assets/10524738/bcf3d57a-cdbb-46f0-ac2a-b0af5d9481cf)
Right Shuffle:
![image](https://github.com/oap-project/gluten/assets/10524738/2dbe9311-ecd8-42d5-9862-00c480f1d001)

After:
Left Shuffle:
![image](https://github.com/oap-project/gluten/assets/10524738/426a7fc6-7052-4dbf-ab59-2fb3c8c7ec40)
Right Shuffle:
![image](https://github.com/oap-project/gluten/assets/10524738/4317e883-b760-42ce-8bf6-edc345c25fe5)

### Spark version

Spark-3.3.x

**Comment by zhli1142015** [comment]
cc @zhouyuan , thanks.

**Comment by ulysses-you** [comment]
@zhli1142015  do you mean before is 2024.1.15 and the after is 2024.1.26 ?

**Comment by marin-ma** [comment]
Could you also provide the "data size" metrics in `ColumnarBroadcaseExchange`? Here's an example:

![image](https://github.com/oap-project/gluten/assets/52736607/9d3ee87e-f2d5-44e9-9ff1-29623664ff8e)

**Comment by marin-ma** [comment]
We modified the value of "data size" to the value of "uncompressed size" metric, and removed "uncompressed size" in https://github.com/oap-project/gluten/pull/4428

Using "data size" as the hint for AQE could be inaccurate, as it is the sum of the allocated memory, not the serialized bytes written.

Here's what we found on Gluten 1.1, tpcds q95, the "data size" from the ColumnarBroadcastExchange is 1848.7KB, but the "data size" from the ColumnarExchange is 4MB (ColumnarExchange -> AQE ShuffleRead (local) -> ColumnarBroadcastExchange), which means the broadcast size hint to AQE is much larger than the actual broadcasted size. The "data size" in ColumnarBroadcastExchange is accumulated by the native columnar batch serializer.

![image](https://github.com/oap-project/gluten/assets/52736607/5a337e95-8e49-4bbf-804a-b31e04cfc5c3)
![image](https://github.com/oap-project/gluten/assets/52736607/65307d34-6349-4487-bb6e-3a82c466c203)


With #4428, the two "data size" metrics can match.

![image](https://github.com/oap-project/gluten/assets/52736607/9c3c9cf9-4f87-42b8-8639-5ab870d34ee5)
![image](https://github.com/oap-project/gluten/assets/52736607/91947459-bd54-41d6-b3af-fb2bcb80a7ce)

**Comment by zhli1142015** [comment]
Thanks @marin-ma for your expaintain.
Here is the broard cast exchange: 
![image](https://github.com/oap-project/gluten/assets/10524738/aa4030b9-ae28-476f-8130-73e113583c5a)

By the way, here is the data of `datasize`.
                     vanilla spark, gluten before #4428, gluten after #4428
left shuffle:   27.4M,             1562.5M,                      15.7M
right shuffle:  349.4M,             430.9M,                        175.5M

Our observation indicates that #4428 has altered the data size for left/right shuffles, making them smaller than the values by vanilla Spark. (Previously, they were actually larger than vanilla Spark's values.) If this adjustment is expected, can we infer that when utilizing Gluten, the shuffle data size will consistently be smaller than that in vanilla Spark? Given the disparity from vanilla Spark's values, guidance may be necessary on how to fine-tune the `spark.sql.autoBroadcastJoinThreshold` setting when running with Gluten.
Thanks.

**Comment by ulysses-you** [comment]
@zhli1142015 it seems the behavior of changing from velox columnar batch size to arrow buffer size:
- before, the data size is 1562.5 MB, the num rows is 154755, then the size per row is about 10KB
- after , the data size is 15.7 MB, the num rows is 154755, then the size per row is about 0.1KB

So, I wonder what does the data actually look like ? Can you show the schema for this shuffle and show some rows?

**Comment by zhli1142015** [comment]
Below is the plan of the shuffle, I use 1TB TPCDS dataset.

```
(151) ColumnarExchange
Input [13]: [hash_partition_key#614, ss_sales_price#15, s_store_name#51, s_state#70, s_zip#71, c_first_name#105, c_last_name#106, c_birth_country#111, i_current_price#80, i_size#90, i_color#92, i_units#93, i_manager_id#95]
Arguments: hashpartitioning(c_birth_country#111, s_zip#71, 258), ENSURE_REQUIREMENTS, [ss_sales_price#15, s_store_name#51, s_state#70, s_zip#71, c_first_name#105, c_last_name#106, c_birth_country#111, i_current_price#80, i_size#90, i_color#92, i_units#93, i_manager_id#95], [plan_id=7090], [id=#7090]
```

**Comment by marin-ma** [comment]
> Our observation indicates that https://github.com/oap-project/gluten/pull/4428 has altered the data size for left/right shuffles, making them smaller than the values by vanilla Spark. (Previously, they were actually larger than vanilla Spark's values.) 

Yes. In vanilla spark, the `dataSize` metrics is the accumulation of the size of `UnsafeRow`, which equals to the concept of "serialized in-memory/uncompressed data size". Before #4428, `dataSize` in ColumnarExchange was collected from the total allocated memory of the input batch size for shuffle, which can be much larger than the actual serialized uncompressed data size.
The reason Gluten has a smaller data size is because the raw data representation of Gluten is different from Spark's UnsafeRow. In most cases, Gluten has a more compact memory layout than Vanilla Spark.

> If this adjustment is expected, can we infer that when utilizing Gluten, the shuffle data size will consistently be smaller than that in vanilla Spark?

The 'dataSize' metric does not represent the shuffled data size. To measure the shuffled data size, we should consider three other metrics: "shuffle bytes written", "local bytes read", and "remote bytes read".
shuffle bytes written = local bytes read + remote bytes read. "shuffle bytes written" is collected from the size of the shuffle data file, which equals to the compressed data size if shuffle compression is enabled. (The compressed size can be slightly larger than the uncompressed size in some bad cases though)
For both "dataSize" and "shuffle bytes written", we cannot guarantee that they are smaller than Vanilla spark. However, based on our observations, they are smaller in most cases, and large but close to Vanilla spark in some cases.

To summarize, 1) The "dataSize" before #4428 was inaccurate. 2) We cannot 100% sure that Gluten "dataSize" is smaller than Vanilla Spark.

> Given the disparity from vanilla Spark's values, guidance may be necessary on how to fine-tune the `spark.sql.autoBroadcastJoinThreshold` setting when running with Gluten.

The current implementation of BHJ in Gluten still needs optimization. To be short, instead of broadcasting the HashTable, Gluten directly broadcasts the raw data from Shuffle reader and builds HashTable in each executor task threads (This is because the native backend lack support for de/serializing HashTable). Due to the adjustments in the "dataSize" metrics, it's recommended to lower the broadcast threshold for Gluten. In the long term, we will support broadcasting HashTable in Gluten.

**Comment by zhli1142015** [comment]
Thanks, make sense to me.

**Comment by zhli1142015** [comment]
> To be short, instead of broadcasting the HashTable, Gluten directly broadcasts the raw data from Shuffle reader and builds HashTable in each executor task threads (This is because the native backend lack support for de/serializing HashTable)

BTW, does this mean we don't need to duplicate hash table build for broad cast side after above optimization and do we have any time line for it?
Thanks.

**Comment by FelixYBW** [comment]
> BTW, does this mean we don't need to duplicate hash table build for broad cast side after above optimization and do we have any time line for it? Thanks.

@zhouyuan will take a look of old PR which build single hash table in all task threads and shared among tasks. The final solution is to broadcast hash table which needs too many changes in Velox, so not planned yet.

**Comment by zhli1142015** [comment]
Thanks, get it.
