### ISSUE TITLE
Jar conflicts on Arrow and Protobuf between Vanilla Spark and Gluten

### ISSUE THREAD

**Issue by zhztheplayer** [oap-project/gluten#789]
I see we have extended a PR to fix this then revert it.

https://github.com/oap-project/gluten/commit/cc6d264ccb9999f19584d1021724fed0f6df4c3b
https://github.com/oap-project/gluten/commit/74c36780f30664cae0ebf9d8ce92ff16c73442f9

@CodingCat We can discuss what have to do about the issue in this thread

**Comment by CodingCat** [comment]
yeah, as mentioned by @zzcclp , the original PR leads to the project loading failure in IDEA and therefore the workflow of people used to using that for development is broken 

the root cause  analysis is following:

1. maven "implements" cross-module based on jar. i.e. if module B depends on module A, module A is packed as a jar first which is taken by B as a dependency
2.  IDEA "implements" cross-module dependency by simply compiling classes
3.  shade plugin relocate classes when packing the jar 

so when people uses IDEA to develop with the changed code from "import x.y.z" to "import shade.x.y.z", it cannot find the dependency

I am proposing 

1. use gradle for the whole project as gradle is much better to handle such issues and based on my experience of managing a complicated JAVA/Scala mono repo , you can always find some solution with gradle for various issues
2. developers have to get a hacky workflow by building jars first and then load to IDEA ... it is with the minimum change, but may bring more complexities and frictions when , e.g. , run a unit test with a updated gluten-core jar...
3. don't touch...if we cannot get the agreement on solution, we have to push it to later...but TBH, it is just the worst choice to me

**Comment by zhztheplayer** [comment]
Was this proved a correct usage of dependency shading?
https://github.com/oap-project/gluten/commit/cc6d264ccb9999f19584d1021724fed0f6df4c3b#diff-5c796f2425c83beae6bafec60f1fca955c4f21f2b22a8961ca87110bd1bd6906L18-L24

Some questions here:

1. What happened in IDEA if at least running "mvn install" once?
2. What happened if we shade on the assembly jar rather than `gluten-core` jar?

**Comment by CodingCat** [comment]
> What happened if we shade on the assembly jar rather than gluten-core jar?

this is a good question, I was discussing with @PHILO-HE . The reason I discard here is that, I found the eventual jar will contain two copies of pb, one for relocated, the other is not relocated....I put shade plugin in root pom.xml, in theory, every module should get relocated when being packed into a jar, but still....I checked `mvn dependency:tree`, everything looks fine so I suspect if it is a bug of shade plugin 


![image](https://user-images.githubusercontent.com/678008/210477997-663b2dca-1dc2-4e65-bd24-85879b3ef702.png)


![image](https://user-images.githubusercontent.com/678008/210478029-be50ab2a-93ac-4d82-bc73-205c951680a9.png)

**Comment by zhztheplayer** [comment]
> I put shade plugin in root pom.xml

Does this make sense to apply shade plugin on the bundled jar generated by `maven-assembly-plugin`? e.g. https://github.com/oap-project/gluten/blob/main/package/velox/spark32/pom.xml 

I recalled that (correct me if I was wrong) `maven-shade-plugin` could do the similar work with `maven-assembly-plugin` to generate a bundled jar but with some classes to be shaded.

**Comment by CodingCat** [comment]
so I spent another few hours in this problem, I don't think anything new is found, please check the following 

1. I repeated what my original PR did. However, we  still fell into the problem of IDEA setup, unless we explicitly add the built gluten-core jar to the dependency of gluten-data (FYI @PHILO-HE , mvn install before running the test doesn't work here). This approach will bring a lot of unknowns, e.g. when you explicitly add a gluten-core.jar but simultaneously keep the cross-module dependency between gluten-core and gluten-data, which one will take precedence is unclear. 

2. only add shade plugin in package/velox directory, it doesn't work at all. The protobuf classes are not relocated at all (I think the reason is that shade plugin only takes care of the dependency defined in the same pom.xml, in this case, since protobuf is brought by gluten-core so that it cannot be covered)

3. add shade plugin in the root pom.xml, same as 1, we need to deal with the IDEA setup problem

**Comment by jinchengchenghh** [comment]
Maybe you can shade in the directory `package/pom.xml` like `hud` https://github.com/apache/hudi/blob/master/packaging/hudi-spark-bundle/pom.xml#L213-L214

**Comment by zhztheplayer** [comment]
@CodingCat I've create a PR as prove-of-concept to use shade plugin instead of assembly plugin:

https://github.com/oap-project/gluten/pull/837

Would you like to check on the changes to see if it works on your side?

**Comment by zhztheplayer** [comment]
https://github.com/oap-project/gluten/commit/2611bbea0797a558270b8dab74fb007953c96ff2
