### ISSUE TITLE
Can we separate native dynamic library from build generated jars?

### ISSUE THREAD

**Issue by Yohahaha** [oap-project/gluten#972]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps developers understand the context and *why* for this feature, in addition to  the *what*)

Native dynamic library (libvelox.so libspark_columnar_jni.so, etc) was copied into final jars when execute `mvn package xxx` currently. 
If we only want to modify cpp code and regenerate dynamic library , it would take long time to rebuild final jars.

Can we use `LD_LIBRARY_PATH` or other similar mechanism to avoid this?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/34979747/218918530-95f39ea2-f389-47ef-bbf6-c420eb189717.png)

**Comment by FelixYBW** [comment]
We packaged the libraries built from source because spark can help us to distribute to remote machine. Otherwise you have to copy the lib to each worker once you modified some code. 

We currently can build the library seperately by build_arrow_for_velox.sh, build_velox.sh and cmake -DBUILD_VELOX_BACKEND=ON under cpp. Then you can replace the lib in the jar by jar-uvf xxx
